### ISSUE TITLE
[Mobile] Unable to select multiple skills

### ISSUE THREAD

**Issue by AdvMaple** [heydevs-io/customer-feedback#1]
# Description
Selecting multiple skills on mobile is unstable. List not remember chosen skills.

# Desire behavior
Able to select multiple skills in list, when clicking "Save" all the selected skills will be remember.

# Relicate Video
https://github.com/heydevs-io/customer-feedback/assets/46006210/23ffc06d-3d4e-4370-b317-165956076539

**Comment by Gacucky** [comment]
Hi @AdvMaple, 
Sorry for the late response and thank you for your report.
We have fixed the above issued in the new version of our app.
Best regards,
Andy.
